### ISSUE TITLE
problem about code

### ISSUE THREAD

**Issue by ccccchenllll** [LiaoYun0x0/Feature-Matching-and-Position-Matching-between-Optical-and-SAR#1]
您好，我在wins10，python3.7，pytorch1.4.0版本下运行您的程序，但是在加在模型的时候，提示我的版本过低，请问下我该用什么版本

**Comment by LiaoYun0x0** [comment]
可以发一下报错具体内容吗，方便于我再更新一下requirements

**Comment by ccccchenllll** [comment]
> 可以发一下报错具体内容吗，方便于我再更新一下requirements
错误如下：
Traceback (most recent call last):
  File "C:/Users/LC/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 361, in <module>
    embede_model,_ = model_choose(model_path)
  File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 136, in model_choose
    load_model(ldm_model,model_path)
  File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 143, in load_model
    checkpoint = torch.load(model_path,map_location='cuda:0')
  File "C:\Users\qq\anaconda3\envs\pytorch_envs_140\lib\site-packages\torch\serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "C:\Users\qq\anaconda3\envs\pytorch_envs_140\lib\site-packages\torch\serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at ..\caffe2\serialize\inline_container.cc:132)
(no backtrace available)

**Comment by LiaoYun0x0** [comment]
更新pytorch到1.6看看，你的pytorch版本太低

**Comment by ccccchenllll** [comment]
> 更新pytorch到1.6看看，你的pytorch版本太低

您好，我更新到了1.6。但是还是遇到了问题。
Traceback (most recent call last):
  File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 371, in <module>
    mc,me,mex,mey,kpt_info = validate(embede_model,fp_detector,data_path,save_path)
  File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 330, in validate
    x,y = opt_path.split('/')[-1].split('.')[0].split('_')[2:]
ValueError: too many values to unpack (expected 2)

请问下这个如何更改？

**Comment by ccccchenllll** [comment]
您好，不好意思再次打扰您。请问下test-image里面图片的命名是有什么特殊意思吗？比如opt_0_144_95中的0、144、95，因为0,144,95与validate中的x，y有关。如果我换个数据集的话，这个程序运行效果就会很差。问题有点多，还望赐教，非常感谢！

**Comment by 2970765122** [comment]
> 您好，我在wins10，python3.7，pytorch1.4.0版本下运行您的程序，但是在加在模型的时候，提示我的版本过低，请问下我该用什么版本

您好 这个代码里面那个old一直划线请问怎么改啊 运行不了啊

**Comment by NaNtaisuike** [comment]
> > 更新pytorch到1.6看看，你的pytorch版本太低
> 
> 您好，我更新到了1.6。但是还是遇到了问题。 Traceback (most recent call last): File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 371, in mc,me,mex,mey,kpt_info = validate(embede_model,fp_detector,data_path,save_path) File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 330, in validate x,y = opt_path.split('/')[-1].split('.')[0].split('_')[2:] ValueError: too many values to unpack (expected 2)
> 
> 请问下这个如何更改？

朋友你好，我遇到了同样的问题，请问一下你解决了吗，我看到好多人都有这个问题

**Comment by NaNtaisuike** [comment]
> > 更新pytorch到1.6看看，你的pytorch版本太低
> 
> 您好，我更新到了1.6。但是还是遇到了问题。 Traceback (most recent call last): File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 371, in mc,me,mex,mey,kpt_info = validate(embede_model,fp_detector,data_path,save_path) File "C:/Users/qq/Desktop/Feature-Matching-and-Position-Matching-between-Optical-and-SAR-main/location_demo.py", line 330, in validate x,y = opt_path.split('/')[-1].split('.')[0].split('_')[2:] ValueError: too many values to unpack (expected 2)
> 
> 请问下这个如何更改？

你好我解决了，把后面的2变成3
